### ISSUE TITLE
macro errors

### ISSUE THREAD

**Issue by ArneDJ** [septag/dds-ktx#1]
I try to compile it in a simple main.c file:
```
#define DDSKTX_IMPLEMENT
#include "dds-ktx.h"

int main(void)
{
	return 0;
}
```
But get the following macro errors:

dds-ktx.h: In function ‘ddsktx__parse_ktx’:
dds-ktx.h:911:51: error: macro "ddsktx_memcmp" requires 3 arguments, but only 2 given
  911 |     if (ddsktx_memcmp(header.id, sizeof(header.id)) == 0) {
      |                                                   ^
In file included from main.c:2:
dds-ktx.h:464: note: macro "ddsktx_memcmp" defined here
  464 | #   define ddsktx_memcmp(_ptr1, _ptr2, _num) memcmp((_ptr1), (_ptr2), (_num))
      | 
In file included from main.c:2:
dds-ktx.h:911:9: error: ‘ddsktx_memcmp’ undeclared (first use in this function)
  911 |     if (ddsktx_memcmp(header.id, sizeof(header.id)) == 0) {
      |         ^~~~~~~~~~~~~
dds-ktx.h:911:9: note: each undeclared identifier is reported only once for each function it appears in
dds-ktx.h: In function ‘ddsktx_get_sub’:
dds-ktx.h:1197:9: warning: implicit declaration of function ‘sx_assert’; did you mean ‘assert’? [-Wimplicit-function-declaration]
 1197 |         sx_assert(0 && "invalid file format");
      |         ^~~~~~~~~
      |         assert

**Comment by septag** [comment]
Sorry for late answer.
ah!! forgot to push the changes from my local repo, it should be fixed now in 5e9d9722cdbe62d90fb5f8b9479981ecb4aaa00a

Thank you
