### ISSUE TITLE
Invalid ktx_id/ktx magic

### ISSUE THREAD

**Issue by iddev5** [septag/dds-ktx#5]
Hello!

There seems to be a problem with loading of KTX files, or specifically with KTX magic at [line 900](https://github.com/septag/dds-ktx/blob/master/dds-ktx.h#L900). 
According to KTX specification (http://github.khronos.org/KTX-Specification/), it should be {0x20, 0x32, 0x30, ...}, but in the file, it is {0x20, 0x31, 0x31...} which is triggering the assertion. Modifying it as suggested above fixed the problem for me.

Thank you.

**Comment by septag** [comment]
Hi,

It's fine actually. I will use the first 4 bytes to detect wither it's DDS or KTX. look at *ddsktx_parse* function, line 1239. remaining 8 bytes will be checked inside parse_ktx function.

Have u seen runtime assertions when loading files ? If so, then there is definitely a bug

You can build and use ctexview example (see README.md) to test it.

**Comment by iddev5** [comment]
There is no problem with detection of format. The "remaining 8 bytes" is causing the assertion: ``ktx: invalid file header`` (line 913). Changing the 2 bytes as shown above fixed it, so I assumed ``ktx__id`` at line 900 is incorrect.

**Comment by septag** [comment]
huh! that is actually a new spec for KTX 2 file format. I wasn't aware of that, so thanks for bringing that up. I have to add KTX2 support later.

but, anyway, it should work fine with most current tools that generate KTX. Khronos' documentation has changed, I couldn't find the older format spec. but check this out:
https://github.com/KhronosGroup/KTX-Software/blob/67a11a84a46de93a02f5d060818c88b98704bf6b/include/ktx.h#L187
