### ISSUE TITLE
Ported the library to C#

### ISSUE THREAD

**Issue by rds1983** [septag/dds-ktx#6]
Just wanted to say that I've ported this library to C#: https://github.com/rds1983/DdsKtxSharp

**Comment by septag** [comment]
Cool. Nice work!
I'll link this to readme

**Comment by rds1983** [comment]
Thanks for the link.
But it has small error.
> DdsKtxSharp: C# Wrapper for dds-ktx by Roman Shapiro
DdsKtxSharp isn't wrapper(aka bindings), but port. C code had been converted to C#.

**Comment by septag** [comment]
sorry my bad.
fixed.
