### ISSUE TITLE
Bug: "ktx: unsupported format" for correct R16UI KTX, easy fix.

### ISSUE THREAD

**Issue by Mikez2015** [septag/dds-ktx#7]
I try decode "terrain_heightmap_r16.ktx" from https://github.com/SaschaWillems/Vulkan and get error "ktx: unsupported format".
PWRTexTool open this file without error.

Way to fix: add to 
`static const ddsktx__ktx_format_info k__translate_ktx_fmt[] `
this:
```
   { DDSKTX__KTX_R16I,DDSKTX__KTX_ZERO, DDSKTX__KTX_RED, DDSKTX__KTX_UNSIGNED_SHORT, }, // R16I
   { DDSKTX__KTX_R16UI, DDSKTX__KTX_ZERO, DDSKTX__KTX_RED, DDSKTX__KTX_UNSIGNED_SHORT,  }, // R16UI
```

**Comment by septag** [comment]
I added those formats. 
thank you
